[project]
name = "demo"
version = "0.1.0"
description = "full stack python app"
readme = "README.md"
authors = [
    { name = "binzhango", email = "zhangbinengr@hotmail.com" }
]
requires-python = ">=3.7.3"
dependencies = []

[project.scripts]
demo = "demo:main"

